version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: patagon_user
      POSTGRES_PASSWORD: MrV5ghjqzIZaoUqMJBnW7CS9j160EHom
      POSTGRES_DB: patagon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./Backend/.env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    ports:
      - "4003:4003"
    env_file:
      - ./Frontend/.env
    restart: unless-stopped
    networks:
      - app-network

  ngrok:
    image: wernight/ngrok
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=2o8iKMv8qWPABK2pbRR9IUGvo1U_2uwUkJSYZT2uz64vsjxEV
      - NGROK_PORT=backend:3003
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
